project_id = "cfhkldeomlvjpyexkekz"

[functions.search-providers]
verify_jwt = false

[functions.google-calendar-events]
verify_jwt = false

[functions.refresh-google-token]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false
